# .github/workflows/cut-release-branch.yml
name: Reusable Cut Release Branch

on:
  workflow_call:
    inputs:
      release_version:
        description: 'Version of the release (e.g., 1.0.0)'
        required: true
        type: string
      base_branch:
        description: 'Base branch to cut the release from (e.g., main or develop)'
        required: true
        type: string
      git_username:
        description: 'Git username for the commit'
        required: true
        type: string
      git_email:
        description: 'Git email for the commit'
        required: true
        type: string

jobs:
  cut_release_branch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the base branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.base_branch }} # Checkout base branch

      # Step 2: Set up Git user configuration
      - name: Set up Git
        run: |
          git config --global user.name "${{ inputs.git_username }}"
          git config --global user.email "${{ inputs.git_email }}"

      # Step 3: Create the release branch
      - name: Create and push release branch
        run: |
          git checkout -b release/${{ inputs.release_version }}
          git push origin release/${{ inputs.release_version }}

      # Step 4: Confirm branch creation
      - name: Show created branch
        run: |
           echo ' Created and pushed release branch: release/${{ inputs.release_version }} '
