name: Generate SBOM, and Upload

on:
    workflow_call:
      inputs:
        toolchain:
          description: 'Rust toolchain version (e.g., stable, nightly)'
          required: true
          type: string
        target:
          description: 'Compilation target (e.g., x86_64-unknown-linux-gnu)'
          required: true
          type: string
        components:
          description: 'Rust components to install (comma-separated, e.g., clippy, rustfmt, llvm-tools)'
          required: false
          type: string
        rustflags:
          description: 'Rust compiler flags (e.g., -C opt-level=3 -C target-cpu=native -C lto)'
          required: false
          type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      name: Checkout code
      
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ inputs.toolchain }}"
        target: "${{ inputs.target }}"
        components: "${{ inputs.components }}"

    - name: Build the Rust project
      run: cargo build --release

    - name: Install Cargo CycloneDX
      run: cargo install cargo-cyclonedx

    - name: Generate SBOM
      run: |
        cargo cyclonedx --format json --verbose --all >> sbom.json
        cat sbom.json
