# .github/workflows/reusable-workflow.yml

name: Scan Stage

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:


    - name: Install cargo-audit
      run: 
          cargo install cargo-audit
          cargo audit

    - name: Get build metadata
      id: build-metadata
      run: |
        echo "Build ID: $GITHUB_RUN_ID"
        echo "Commit SHA: $GITHUB_SHA"
        echo "Branch: $GITHUB_REF"
      shell: bash
        
