# .github/workflows/reusable-workflow.yml
name: Scan Stage

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain version (e.g., stable, nightly)'
        required: true
        type: string
      target:
        description: 'Compilation target (e.g., x86_64-unknown-linux-gnu)'
        required: false
        type: string
      components:
        description: 'Rust components to install (comma-separated, e.g., clippy, rustfmt, llvm-tools)'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}
        components: ''

    - name: Install cargo-audit
      run: 
          cargo install cargo-audit
          cargo audit

    - name: Get build metadata
      id: build-metadata
      run: |
        echo "Build ID: $GITHUB_RUN_ID"
        echo "Commit SHA: $GITHUB_SHA"
        echo "Branch: $GITHUB_REF"
      shell: bash
        
